requires = [
  "tox>=4.54",
  "tox-uv",
]
envlist = [
    "lint",
    { product = [
        { prefix = "3.", start = 10, stop = 14 },
    ] },
]

[env_run_base]
description = "run tests on Python {py_dot_ver}"
runner = "uv-venv-runner"
package = "uv"
dependency_groups = [
    "test"
]
extras = ["pyodbc"]
commands = [["pytest", "--capture=no"]]

[env.format]
description = "format code"
dependency_groups = ["lint"]
commands = [
    ["ruff", "format", "target_mssql"],
    ["ruff", "check", "--fix", "target_mssql"],
]

[env.lint]
description = "lint code"
dependency_groups = ["lint"]
commands = [
    ["ruff", "format", "--check", "target_mssql"],
    ["ruff", "check", "target_mssql"],
]
